# Generated by Django 5.2.1 on 2025-05-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0002_rename_drs_dr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr',
            name='dr_license',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='dr license'),
        ),
        migrations.AlterField(
            model_name='dr',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
