# Generated by Django 5.2.1 on 2025-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0003_alter_dr_dr_license_alter_dr_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr',
            name='dr_license',
            field=models.CharField(blank=True, help_text='dr_license -> already exists.', max_length=150, unique=True, verbose_name='dr license'),
        ),
        migrations.AlterField(
            model_name='dr',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
