# Generated by Django 5.2.1 on 2025-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0004_alter_dr_dr_license_alter_dr_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
