# Generated by Django 5.2.1 on 2025-05-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drs', '0004_alter_dr_dr_license_alter_dr_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('date', models.DateField()),
                ('leading_dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='drs.dr')),
            ],
        ),
    ]
