# Generated by Django 5.2.1 on 2025-05-16 12:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('date', models.DateField(verbose_name=datetime.date(2025, 5, 16))),
                ('leading_dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='drs.dr')),
            ],
        ),
    ]
