# Generated by Django 5.2.1 on 2025-05-13 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 15, 30, 36, 875021, tzinfo=datetime.timezone.utc)),
        ),
    ]
