# Generated by Django 5.2.1 on 2025-05-14 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_alter_podcast_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 14, 16, 23, 5, 145284, tzinfo=datetime.timezone.utc)),
        ),
    ]
