# Generated by Django 5.2.1 on 2025-05-16 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_alter_podcast_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2025, 5, 16)),
        ),
    ]
